### ISSUE TITLE
CT100 possible? - error in log (XMPP authentication failure)

### ISSUE THREAD

**Issue by e-i-k-e** [Monschichi/ioBroker.boscheasycontrol#93]
Hello,

I was happy to find your adapter.

I own a CT100, also with access key - password and serial as access data.
My password has 9 characters (10 for me).

I've tried but I'm getting some errors in ioBroker.
Is this not possible with the CT100, or is there another problem?

Another project mentions the CT100.
https://github.com/robertklep/bosch-xmpp/

Help is very much appreciated. :)

ioBroker Log:
`<html>
<body>

boscheasycontrol.0 | 2023-03-11 21:39:20.443 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
boscheasycontrol.0 | 2023-03-11 21:39:20.442 | info | terminating
boscheasycontrol.0 | 2023-03-11 21:39:20.432 | error | Exception-Code: ERR_UNHANDLED_ERROR: Unhandled error. ('XMPP authentication failure')
boscheasycontrol.0 | 2023-03-11 21:39:20.430 | error | Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('XMPP authentication failure') at new NodeError (node:internal/errors:399:5) at Client.emit (node:events:502:17) at Client._handleAuthState (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:295:10) at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:233:12) at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:221:8) at Connection.emit (node:events:513:28) at Connection.onStanza (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:377:10) at StreamParser.<anonymous> (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:231:10) at StreamParser.emit (node:events:513:28) at SaxLtx.<anonymous> (/opt/iobroker/node_modules/@xmpp/streamparser/index.js:69:14) at SaxLtx.emit (node:events:513:28) at SaxLtx._handleTagOpening (/opt/iobroker/node_modules/ltx/lib/parsers/ltx.js:40:12) at SaxLtx.write (/opt/iobroker/node_modules/ltx/lib/parsers/ltx.js:159:18) at StreamParser.write (/opt/iobroker/node_modules/@xmpp/streamparser/index.js:134:17) at Connection.onData (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:310:17) at TLSSocket.emit (node:events:525:35)
boscheasycontrol.0 | 2023-03-11 21:39:20.427 | error | uncaught exception: Unhandled error. ('XMPP authentication failure')
boscheasycontrol.0 | 2023-03-11 21:36:50.370 | info | startup ... done
boscheasycontrol.0 | 2023-03-11 21:36:50.369 | error | XMPP authentication failure
boscheasycontrol.0 | 2023-03-11 21:36:50.283 | error | XMPP authentication failure
boscheasycontrol.0 | 2023-03-11 21:36:48.264 | info | starting. Version 0.1.0 (non-npm: Monschichi/ioBroker.boscheasycontrol#5be36d6c4de6f06e4ad7e73d4abdca4069fee760) in /opt/iobroker/node_modules/iobroker.boscheasycontrol, node: v18.15.0, js-controller: 4.0.24
boscheasycontrol.0 | 2023-03-11 21:36:14.420 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
boscheasycontrol.0 | 2023-03-11 21:36:14.419 | info | terminating
boscheasycontrol.0 | 2023-03-11 21:36:14.411 | error | Exception-Code: ERR_UNHANDLED_ERROR: Unhandled error. ('XMPP authentication failure')
boscheasycontrol.0 | 2023-03-11 21:36:14.409 | error | Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('XMPP authentication failure') at new NodeError (node:internal/errors:399:5) at Client.emit (node:events:502:17) at Client._handleAuthState (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:295:10) at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:233:12) at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:221:8) at Connection.emit (node:events:513:28) at Connection.onStanza (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:377:10) at StreamParser.<anonymous> (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:231:10) at StreamParser.emit (node:events:513:28) at SaxLtx.<anonymous> (/opt/iobroker/node_modules/@xmpp/streamparser/index.js:69:14) at SaxLtx.emit (node:events:513:28) at SaxLtx._handleTagOpening (/opt/iobroker/node_modules/ltx/lib/parsers/ltx.js:40:12) at SaxLtx.write (/opt/iobroker/node_modules/ltx/lib/parsers/ltx.js:159:18) at StreamParser.write (/opt/iobroker/node_modules/@xmpp/streamparser/index.js:134:17) at Connection.onData (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:310:17) at TLSSocket.emit (node:events:525:35)
boscheasycontrol.0 | 2023-03-11 21:36:14.407 | error | uncaught exception: Unhandled error. ('XMPP authentication failure')
boscheasycontrol.0 | 2023-03-11 21:33:44.291 | info | startup ... done
boscheasycontrol.0 | 2023-03-11 21:33:44.289 | error | XMPP authentication failure
boscheasycontrol.0 | 2023-03-11 21:33:44.235 | error | XMPP authentication failure
boscheasycontrol.0 | 2023-03-11 21:33:42.756 | info | starting. Version 0.1.0 (non-npm: Monschichi/ioBroker.boscheasycontrol#5be36d6c4de6f06e4ad7e73d4abdca4069fee760) in /opt/iobroker/node_modules/iobroker.boscheasycontrol, node: v18.15.0, js-controller: 4.0.24
boscheasycontrol.0 | 2023-03-11 21:33:08.898 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
boscheasycontrol.0 | 2023-03-11 21:33:08.897 | info | terminating
boscheasycontrol.0 | 2023-03-11 21:33:08.882 | error | Exception-Code: ERR_UNHANDLED_ERROR: Unhandled error. ('XMPP authentication failure')
boscheasycontrol.0 | 2023-03-11 21:33:08.880 | error | Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('XMPP authentication failure') at new NodeError (node:internal/errors:399:5) at Client.emit (node:events:502:17) at Client._handleAuthState (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:295:10) at Client._handleStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:233:12) at Client.onStanza (/opt/iobroker/node_modules/node-xmpp-client/lib/Client.js:221:8) at Connection.emit (node:events:513:28) at Connection.onStanza (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:377:10) at StreamParser.<anonymous> (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:231:10) at StreamParser.emit (node:events:513:28) at SaxLtx.<anonymous> (/opt/iobroker/node_modules/@xmpp/streamparser/index.js:69:14) at SaxLtx.emit (node:events:513:28) at SaxLtx._handleTagOpening (/opt/iobroker/node_modules/ltx/lib/parsers/ltx.js:40:12) at SaxLtx.write (/opt/iobroker/node_modules/ltx/lib/parsers/ltx.js:159:18) at StreamParser.write (/opt/iobroker/node_modules/@xmpp/streamparser/index.js:134:17) at Connection.onData (/opt/iobroker/node_modules/node-xmpp-core/lib/Connection.js:310:17) at TLSSocket.emit (node:events:525:35)
boscheasycontrol.0 | 2023-03-11 21:33:08.877 | error | uncaught exception: Unhandled error. ('XMPP authentication failure')
boscheasycontrol.0 | 2023-03-11 21:30:38.857 | info | startup ... done
boscheasycontrol.0 | 2023-03-11 21:30:38.856 | error | XMPP authentication failure
boscheasycontrol.0 | 2023-03-11 21:30:38.793 | error | XMPP authentication failure
boscheasycontrol.0 | 2023-03-11 21:30:36.277 | info | starting. Version 0.1.0 (non-npm: Monschichi/ioBroker.boscheasycontrol#5be36d6c4de6f06e4ad7e73d4abdca4069fee760) in /opt/iobroker/node_modules/iobroker.boscheasycontrol, node: v18.15.0, js-controller: 4.0.24
boscheasycontrol.0 | 2023-03-11 21:30:29.696 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
boscheasycontrol.0 | 2023-03-11 21:30:29.695 | info | terminating
boscheasycontrol.0 | 2023-03-11 21:30:29.690 | info | Got terminate signal TERMINATE_YOURSELF
boscheasycontrol.0 | 2023-03-11 21:24:34.679 | error | Serial, Access Key and Password needs to be defined for this adapter to work.
boscheasycontrol.0 | 2023-03-11 21:24:34.611 | info | starting. Version 0.1.0 (non-npm: Monschichi/ioBroker.boscheasycontrol#5be36d6c4de6f06e4ad7e73d4abdca4069fee760) in /opt/iobroker/node_modules/iobroker.boscheasycontrol, node: v18.15.0, js-controller: 4.0.24

</body>
</html>`

Edit: Even shortening the password to 8 characters did not change anything.

**Comment by Monschichi** [comment]
I'm using https://github.com/robertklep/bosch-xmpp/ as backend for this adapter, but I only support CT200, as I only own one of these.

As far as the documentation of bosch-xmpp [suggest](https://github.com/robertklep/bosch-xmpp#nefit-easy) you could change the import https://github.com/Monschichi/ioBroker.boscheasycontrol/blob/5be36d6c4de6f06e4ad7e73d4abdca4069fee760/main.js#L12 and the connection https://github.com/Monschichi/ioBroker.boscheasycontrol/blob/5be36d6c4de6f06e4ad7e73d4abdca4069fee760/main.js#L45 to NefitEasyClient.
But as I don't own a CT100 I can't say if the data points returned from the api are compatible.
